services:
  
  # NGINX API Gateway
  nginx:
    image: nginx:alpine-slim
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

  # Beook Solutions
  beook-solutions:
    image: ghcr.io/marekvonrogall/tools/beook-solutions:latest
    container_name: beook-solutions