name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/**'
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_ACCESS_TOKEN }}

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          
      - name: Build Docker Image
        run: |
          docker-compose -f docker-compose-build.yml build

      - name: Push Docker Image to GHCR
        run: |
          docker-compose -f docker-compose-build.yml push

  deploy:
    name: Deploy to Remote Server
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create deployment directory on the remote server
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} "mkdir -p /root/deployment"
      
      - name: Upload files to remote server
        run: |
          scp -o StrictHostKeyChecking=no ./docker-compose-deploy.yml root@${{ secrets.DROPLET_IP }}:/root/deployment/
          scp -o StrictHostKeyChecking=no ./src/nginx/nginx.conf root@${{ secrets.DROPLET_IP }}:/root/deployment/

      - name: Deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} << 'EOF'
            cd /root/deployment
            docker-compose -f docker-compose-deploy.yml pull
            docker-compose -f docker-compose-deploy.yml down
            docker-compose -f docker-compose-deploy.yml up -d
          EOF
          